#!/usr/bin/env bash
# Provides information about a file named 'school'
if [ -e school ]; then
  echo "school file exists"
  [ ! -s school ] && echo "school file is empty" || echo "school file is not empty"
  [ -f school ] && echo "school is a regular file"
else
  echo "school file does not exist"
fi
